package com.theducksparadise.jukebox.talker;

import java.util.Random;

public class PirateTalker implements Talker {

    private static final String[] verbs = new String[] {
            "abandon",
            "adventure",
            "assault",
            "attack",
            "battle",
            "behead",
            "capsize",
            "capture",
            "challenge",
            "confiscate",
            "curse",
            "escape",
            "explore",
            "fight",
            "hijack",
            "hook",
            "hold",
            "keelhaul",
            "kidnap",
            "kill",
            "lash",
            "lookout",
            "maroon",
            "menace",
            "navigate",
            "parley",
            "pillage",
            "plunder",
            "prowl",
            "quest",
            "raid",
            "ransack",
            "revolt",
            "roam",
            "rob",
            "sabotage",
            "sail",
            "ship",
            "steal",
            "swab",
            "torture",
            "trade",
            "vandalize",
            "vanquish",

    };

    private static final String[] nouns = new String[] {
            "adventure",
            "anchor",
            "armada",
            "arms",
            "bad breath",
            "bandanna",
            "bandit",
            "bandolier",
            "barrel",
            "battle",
            "beach",
            "boatswain",
            "bos'n",
            "bounty",
            "brawl",
            "buccaneer",
            "cannon",
            "cannon balls",
            "captain",
            "cargo",
            "cave",
            "challenge",
            "chest",
            "coast",
            "coastline",
            "coins",
            "compass",
            "conquest",
            "contraband",
            "corpse",
            "corsair",
            "course",
            "crew",
            "criminal",
            "crook",
            "crow's nest",
            "cutlass",
            "curse",
            "dagger",
            "danger",
            "dead reckoning",
            "deck",
            "deck hands",
            "desert island",
            "doubloon",
            "earring",
            "eye patch",
            "fear",
            "first mate",
            "flag",
            "fleet",
            "flotsam and jetsam",
            "fortune",
            "galleon",
            "gangplank",
            "gear",
            "gibbet",
            "gold",
            "greed",
            "grog",
            "gun",
            "gunner",
            "gunpowder",
            "haul",
            "heist",
            "high seas",
            "hook",
            "hold",
            "horizon",
            "hull",
            "hurricane",
            "island",
            "jetsam",
            "jewels",
            "Jolly Roger",
            "keel",
            "knife",
            "land",
            "landlubber",
            "legend",
            "limey",
            "Long John Silver",
            "loot",
            "lore",
            "lucre",
            "maggot",
            "malaria",
            "map",
            "marauder",
            "matiner",
            "mast",
            "mates",
            "mayhem",
            "menace",
            "merchant",
            "musket",
            "mutiny",
            "ocean",
            "old salt",
            "outcasts",
            "parrot",
            "pegleg",
            "pieces of eight",
            "pirate",
            "pistol",
            "plank",
            "plunder",
            "poop deck",
            "privateer",
            "quartermaster",
            "quarters",
            "quest",
            "raid",
            "rat",
            "rations",
            "realm",
            "reckoning",
            "revenge",
            "revolt",
            "riches",
            "rigging",
            "robber",
            "rope",
            "rudder",
            "ruffian",
            "rum",
            "sabotage",
            "sail",
            "sailor",
            "scalawag",
            "scar",
            "scurvy",
            "seas",
            "seaweed",
            "sextant",
            "ship",
            "shipmate",
            "shore",
            "silver",
            "skiff",
            "skull and bones",
            "spoils",
            "swab",
            "swagger",
            "sword",
            "thief",
            "thievery",
            "thug",
            "tides",
            "torture",
            "trade",
            "treachery",
            "treasure",
            "treasure island",
            "truce",
            "vessel",
            "villain",
            "violence",
            "weapons",
            "yellow fever"
    };

    private static final String[] adjectives = new String[] {
            "asea",
            "ashore",
            "asinine",
            "bad",
            "barbaric",
            "blasted",
            "bottom feedin'",
            "brutal",
            "churlish",
            "clammy",
            "cruel",
            "crusty",
            "cutthroat",
            "daft",
            "damned",
            "daring",
            "decrepit",
            "dim",
            "dishonest",
            "disreputable",
            "drunken",
            "dubious",
            "evil",
            "fat",
            "fearsome",
            "feeble",
            "ferocious",
            "fish-like",
            "greedy",
            "hideous",
            "hostile",
            "illegal",
            "ill-gotten",
            "imbecilic",
            "infamous",
            "lawless",
            "misshapen",
            "nautical",
            "New World",
            "notorious",
            "Old World",
            "overboard",
            "predatory",
            "ruthless",
            "sailing",
            "scurvy",
            "smelly",
            "swashbuckling",
            "treacherous",
            "ugly",
            "unkempt",
            "unlawful",
            "unscrupulous",
            "vicious",
            "vile",
            "violent"
    };

    private static final String[] exclamations = new String[] {
            "ahoy",
            "arrrrr",
            "aye-aye",
            "by Neptune's beard",
            "feed the fish",
            "land-ho",
            "lick me cannon balls",
            "matey",
            "shiver-me-timbers",
            "swab the deck",
            "swash me buckles",
            "walk the plank",
            "X marks the spot",
            "yar",
            "yo-ho-ho"
    };


    // %n : noun
    // %v : verb
    // %a : adjective
    // %d : descriptive
    private static final String[] formats = new String[] {
            "%v the %n ye %d",
            "%v the %n and %v the %n! We be lookin' fer %d",
            "%d off the starboard bow",
            "yer %n was a %d",
            "dat be a %a, %a, %a, %n ye gots there",
            "did I ask ye to %v? Ye %d from the %a isles",
            "ye think ye are good 'nuf to %v me %n? %d",
            "all hands on deck! We gots a %d here",
            "that makes me want t' %v, %v, then %v me %a %n",
            "where did ye hear about me %d? I told nobody but me %n",
            "%a, %a, %a, %a, %n and %n",
            "wots dis %d ye keep %v about?",
            "I hears ye, no need to %v yer %n",
            "me favorite shanty is %v the %d by %a",
            "whatever, yer %n was a %n",
            "%a, %d and %v the %d",
            "'tis a fine ship. Except for the %n",
            "drunker than a %d who %v on a %n",
            "does this hat make me %n look %a?",
            "I hid me treasure behind the %d",
            "I heard a song about %d and it reminded me of ye and yer %a %n",
            "who %v the %n dis time?",
            "well mine is as %a as a %d",
            "me mom always said if ye can't %v then ye should %v instead",
            "did I be askin' yer opinion on %d?",
            "when we go ashore, watch out for the %d",
            "can ye just %v already?",
            "%a %n on a %a %n",
            "I not be drunk, just a %d",
            "%v the %n 'til it's %a",
            "your momma's so %a, she %v the %n",
            "you smell worse than a %d",
            "I thought that was ye, or maybe a %d",
            "you be uglier than an %a %n, and that's worse than a %d",
            "I usually don't respond to a %a %n, especially one as stupid as a %d",
            "did ye want to hear a song? Or are you just going to %v your %n like a %a %n",
            "oh we has a regular %d here",
            "you're not even fit to be a %a %n on me ship",
            "is that a %d in your pocket, or are ye just an idiot",
            "I'm usually nicer than a %d... but then I met yer %n",
            "I've never seen a pirate as %a, %a, or %a as this %n",
            "It's me favorite %d talking to me again, must be drunk",
            "I'd rather eat a %d than talk to ye",
            "So do ye still %v the %n",
            "I heard ye were in the brig after ye %v the %n",
            "You look right %n-like",
            "Ye call yourself a pirate? I call ye a %d",
            "Ye earn the %n trophy for bein' so %a",
            ""
    };

    @Override
    public String talk() {
        Random random = new Random();
        String response = replacePlaceholders(random, formats[random.nextInt(formats.length)], nouns, "%n");
        response = replacePlaceholders(random, response, adjectives, "%a");
        response = replacePlaceholders(random, response, verbs, "%v");

        while (response.contains("%d")) {
            response = response.replaceFirst("%d", getDescriptiveNoun(random));
        }

        return exclaim(random, response);
    }

    private String getDescriptiveNoun(Random random) {
        String descriptiveNoun = "";

        int adjectiveCount = random.nextInt(4);
        for (int i=0; i<adjectiveCount; i++) {
            if (i > 0) descriptiveNoun += ", ";
            descriptiveNoun += adjectives[random.nextInt(adjectives.length)];
        }

        return descriptiveNoun + " " + nouns[random.nextInt(nouns.length)];
    }

    private String exclaim(Random random, String string) {
        if (random.nextInt(3) == 0) string = exclamations[random.nextInt(exclamations.length)] + (string.length() > 0 ? ", " : "") + string;
        if (random.nextInt(3) == 0 && !string.endsWith("?")) string += (string.length() > 0 ? ", " : "") + exclamations[random.nextInt(exclamations.length)];

        return string + "!";
    }

    private String replacePlaceholders(Random random, String string, String[] values, String placeholder) {
        while (string.contains(placeholder)) {
            string = string.replaceFirst(placeholder, values[random.nextInt(values.length)]);
        }

        return string;
    }

}
